// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkMrmw_XQpnI8hPWoshDXCv4kIwM5AsKI',
    appId: '1:976619927198:web:e68057911688b2e90fed8f',
    messagingSenderId: '976619927198',
    projectId: 'smartattendanceapp-bc2fe',
    authDomain: 'smartattendanceapp-bc2fe.firebaseapp.com',
    storageBucket: 'smartattendanceapp-bc2fe.firebasestorage.app',
    measurementId: 'G-1G9WBTY3XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHxjGTGYIuKYTgZvM2WNz5ex2OMq0aS2I',
    appId: '1:976619927198:android:bab862c7dc3156f60fed8f',
    messagingSenderId: '976619927198',
    projectId: 'smartattendanceapp-bc2fe',
    storageBucket: 'smartattendanceapp-bc2fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFHbk5Ry9WESbx9yxmPElkDb4rQkn_s90',
    appId: '1:976619927198:ios:8d5ea611741582950fed8f',
    messagingSenderId: '976619927198',
    projectId: 'smartattendanceapp-bc2fe',
    storageBucket: 'smartattendanceapp-bc2fe.firebasestorage.app',
    iosBundleId: 'com.example.smartAttendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFHbk5Ry9WESbx9yxmPElkDb4rQkn_s90',
    appId: '1:976619927198:ios:8d5ea611741582950fed8f',
    messagingSenderId: '976619927198',
    projectId: 'smartattendanceapp-bc2fe',
    storageBucket: 'smartattendanceapp-bc2fe.firebasestorage.app',
    iosBundleId: 'com.example.smartAttendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkMrmw_XQpnI8hPWoshDXCv4kIwM5AsKI',
    appId: '1:976619927198:web:78220a84c0cf28d70fed8f',
    messagingSenderId: '976619927198',
    projectId: 'smartattendanceapp-bc2fe',
    authDomain: 'smartattendanceapp-bc2fe.firebaseapp.com',
    storageBucket: 'smartattendanceapp-bc2fe.firebasestorage.app',
    measurementId: 'G-W0G0TVFESJ',
  );

}
